### ISSUE TITLE
从less（css）的角度实现1px边框

### ISSUE THREAD

**Issue by ViYaYaYa** [ViYaYaYa/MY_Gist#14]
```less
.border1px {
  position: relative;
  &:after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    box-sizing: border-box;
    width: 100%;
    height: 100%;
    transform: scale(1);
    transform-origin: left top;
    html[data-dpr="2"] & {
      width: 200%;
      height: 200%;
      transform: scale(0.5);
    }
    html[data-dpr="3"] & {
      width: 300%;
      height: 300%;
      transform: scale(0.333333);
    }
    html[data-dpr="4"] & {
      width: 400%;
      height: 400%;
      transform: scale(0.25);
    }
  }
}

/**
 * 调用方式
 * 0. 需配合common.less的.border1px全局原子类使用
 * 1. 元素通过原子类添加.border1px
 * 2. 可直接在after修改border设定 / 或调用mixin(@color, @radius)进行设定\
 *
 * 用例:
 * <div class="boder1px box"></div>
 * .box {
 *   .border1px(left, #999);
 *   .border1px(#666);
 * }
 */
.border1px(@direction, @color: #cccccc) when (iskeyword(@direction)) {
  &:after {
    border-@{direction}: 1px solid @color;
  }
}

.border1px(@color: #cccccc) when (iscolor(@color)) {
  &:after {
    border: 1px solid @color;
  }
}
```
